apiVersion: v1
kind: Service
metadata:
  name: rollingstone-templateapi
  labels:
    app: rollingstone-templateapi
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: rollingstone-templateapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingstone-templateapi
  labels:
    app: rollingstone-templateapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollingstone-templateapi
  template:
    metadata:
      labels:
        app: rollingstone-templateapi
    spec:
      containers:
        - name: rollingstone-templateapi
          image: vijayakrishnajava/rollingstone-templateapi
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
