---
- name: Create pods using deployment 
  hosts: localhost
  vars:
    appName: "rollingstone-templateapi"
  become: true
  user: root
  tasks: 
  - name: test dir
    command: "pwd"
  - name: create a configmap
    command: "kubectl apply -f k8s-config.yaml"
    args:
      chdir: "/home/ansadmin/jenkins/{{ appName }}/workspace"
  - name: create a role
    command: "kubectl apply -f k8s-role.yaml"
    args:
      chdir: "/home/ansadmin/jenkins/{{ appName }}/workspace"
  - name: create a deployment
    command: "kubectl apply -f udeploy.yaml"
    args:
      chdir: "/home/ansadmin/jenkins/{{ appName }}/workspace"
  - name: update deployment with new pods if image updated in docker hub
    command: "kubectl rollout restart deployment.v1.apps/{{ appName }}"
    
