apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: vijayakrishnajava/rollingstone-templateapi
      jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
      - k8s-role.yaml
      - k8s-config.yaml
      - k8s-deployment.yaml
